CREATE TABLE IF NOT EXISTS `#__ra_delivery_events` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `provider_name` varchar(40) NOT NULL DEFAULT 'smtp2go',
  `api_site_id` int unsigned NOT NULL DEFAULT 0,
  `email_id` varchar(120) DEFAULT NULL,
  `event_type` varchar(40) NOT NULL,
  `event_date_utc` datetime NOT NULL,
  `recipient` varchar(255) DEFAULT NULL,
  `sender` varchar(255) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `smtp_response` mediumtext,
  `username` varchar(120) DEFAULT NULL,
  `subaccount_name` varchar(120) DEFAULT NULL,
  `host` varchar(120) DEFAULT NULL,
  `outbound_ip` varchar(64) DEFAULT NULL,
  `byte_size` int DEFAULT NULL,
  `raw_payload` longtext,
  `fetched_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT 0,
  `modified` datetime DEFAULT NULL,
  `modified_by` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_provider_event` (`provider_name`, `email_id`, `event_type`, `event_date_utc`, `recipient`),
  KEY `idx_event_date` (`event_date_utc`),
  KEY `idx_event_type` (`event_type`),
  KEY `idx_email_id` (`email_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
